export type Props = {
  name: string;
  surname: string;
  email: string;
  phone: string;
  info: string;
  image: any;
  setImage: any;
  showImage: boolean;
  position: string;
  employer: string;
  startDate: string;
  endDate: string;
  experience: string;
  handleAddInput: any;
  school: string;
  degree: string;
  endOfStudy: string;
  bio: string;
  experienceContent: any;
  educationContent: any;
  imageData: any;
  setName?: React.Dispatch<React.SetStateAction<string>>;
};
